// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestOData.Context;

#nullable disable

namespace TestOData.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20230829132913_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("TestOData.Models.DataFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FileId");

                    b.ToTable("DataFiles");
                });

            modelBuilder.Entity("TestOData.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataFileRef")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("DataFileRef");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestOData.Models.User", b =>
                {
                    b.HasOne("TestOData.Models.DataFile", "FileRefNavigation")
                        .WithMany()
                        .HasForeignKey("DataFileRef");

                    b.Navigation("FileRefNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
